export const SET_DOUGH = "SET_DOUGH";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_SAUCES = "SET_SAUCES";
export const SET_SIZES = "SET_SIZES";
export const SET_MISC = "SET_MISC";

export const UPDATE_PIZZA = "UPDATE_PIZZA";
export const UPDATE_PIZZA_NAME = "UPDATE_PIZZA_NAME";
export const UPDATE_PIZZA_DOUGH = "UPDATE_PIZZA_DOUGH";
export const UPDATE_PIZZA_SAUCE = "UPDATE_PIZZA_SAUCE";
export const UPDATE_PIZZA_SIZE = "UPDATE_PIZZA_SIZE";
export const UPDATE_PIZZA_INGREDIENT_COUNT = "UPDATE_PIZZA_INGREDIENT_COUNT";
export const UPDATE_PIZZAS_QUANTITY = "UPDATE_PIZZAS_QUANTITY";
export const UPDATE_PIZZA_IN_CART = "UPDATE_PIZZA_IN_CART"

export const UPDATE_ADDITION_PRODUCT_COUNT = "UPDATE_ADDITION_PRODUCT_COUNT";

export const RESET_PIZZA = "RESET_PIZZA";
export const RESET_CART = "RESET_CART";

export const PUT_PIZZA_TO_CART = "PUT_PIZZA_TO_CART";

export const CONFIRM_ORDER = "CONFIRM_ORDER";
